name: Build Sofia Mobile APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Puxar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar as bagaceiras do sistema (Dependências)
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Instalar Buildozer e Cython
        run: |
          pip install --upgrade buildozer "Cython==0.29.33" virtualenv

      - name: Botar o bixo pra compilar
        run: |
          buildozer -v android debug

      - name: Salvar o APK pronto pra tu baixar
        uses: actions/upload-artifact@v4
        with:
          name: SofiaMobile-APK
          path: bin/*.apk
